// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtwagmphvyvdlggtlnqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0d2FnbXBodnl2ZGxnZ3RsbnF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDEwODcsImV4cCI6MjA2MzQxNzA4N30.NjVi9W3ZY4pPo0MwBthhc2CbOoC7WuEvCSNjjeSomoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);